name: Publish Nightly DockerHub Image

on:
  schedule:
    - cron: '0 17 * * *'
  # Allow manual trigger
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  DOCKERHUB_IMAGE_NAME: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/nimtable
  DOCKERHUB_FRONTEND_IMAGE_NAME: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/nimtable-web

jobs:
  build-and-push-images:
    strategy:
      matrix:
        arch_config:
          - {arch: 'arm64'}
          - {arch: 'amd64'}
        image_config:
          - type: 'backend'
            dockerfile: './docker/Dockerfile'
            dockerhub_image_name: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/nimtable
          - type: 'frontend'
            dockerfile: './docker/Dockerfile.frontend'
            dockerhub_image_name: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/nimtable-web
    runs-on: ${{ matrix.arch_config.arch == 'arm64' && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata for Docker (${{ matrix.image_config.type }})
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ matrix.image_config.dockerhub_image_name }}
          tags: |
            type=raw,value=nightly-${{matrix.arch_config.arch}}
            type=raw,value=nightly-${{ github.sha }}-${{matrix.arch_config.arch}}

      - name: Build and push Docker image (${{ matrix.image_config.type }})
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.image_config.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # create multi-arch image
  merge-docker-manifest:
    runs-on: ubuntu-latest
    needs: [build-and-push-images]
    steps:
      - name: Login to DockerHub (merge Docker manifest)
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Create and push manifest images to DockerHub (nightly)
        uses: Noelware/docker-manifest-action@0.4.3
        with:
          inputs: ${{ env.DOCKERHUB_IMAGE_NAME }}:nightly
          images: ${{ env.DOCKERHUB_IMAGE_NAME }}:nightly-amd64,${{ env.DOCKERHUB_IMAGE_NAME }}:nightly-arm64
          push: true
      - name: Create and push manifest images to DockerHub (nightly-sha)
        uses: Noelware/docker-manifest-action@0.4.3
        with:
          inputs: ${{ env.DOCKERHUB_IMAGE_NAME }}:nightly-${{ github.sha }}
          images: ${{ env.DOCKERHUB_IMAGE_NAME }}:nightly-${{ github.sha }}-amd64,${{ env.DOCKERHUB_IMAGE_NAME }}:nightly-${{ github.sha }}-arm64
          push: true
      - name: Create and push manifest images for Frontend to DockerHub (nightly)
        uses: Noelware/docker-manifest-action@0.4.3
        with:
          inputs: ${{ env.DOCKERHUB_FRONTEND_IMAGE_NAME }}:nightly
          images: ${{ env.DOCKERHUB_FRONTEND_IMAGE_NAME }}:nightly-amd64,${{ env.DOCKERHUB_FRONTEND_IMAGE_NAME }}:nightly-arm64
          push: true
      - name: Create and push manifest images for Frontend to DockerHub (nightly-sha)
        uses: Noelware/docker-manifest-action@0.4.3
        with:
          inputs: ${{ env.DOCKERHUB_FRONTEND_IMAGE_NAME }}:nightly-${{ github.sha }}
          images: ${{ env.DOCKERHUB_FRONTEND_IMAGE_NAME }}:nightly-${{ github.sha }}-amd64,${{ env.DOCKERHUB_FRONTEND_IMAGE_NAME }}:nightly-${{ github.sha }}-arm64
          push: true

